import { mysqlTable, varchar, text, mysqlEnum, date, datetime, timestamp, json, int } from 'drizzle-orm/mysql-core'

export const users = mysqlTable('users', {
  id:               varchar('id', { length: 36  }).primaryKey(),
  login:            varchar('login', { length: 255 }).notNull(),
  password:         varchar('password', { length: 255 }).notNull(),
  name:             varchar('name', { length: 255 }).notNull(),
  role:             mysqlEnum('role', ['admin', 'user']).notNull().default('user'),
  image:            varchar('image', { length: 255 }),
  refresh_token:    text('refresh_token'),
  ai_system_prompt: text('ai_system_prompt'),
  vk_access_token:  text('vk_access_token'),
  vk_refresh_token: text('vk_refresh_token'),
  vk_token_expires_at: timestamp('vk_token_expires_at'),
  vk_user_id:       varchar('vk_user_id',       { length: 32  }),
  telegram_session: text('telegram_session'),
  last_social_request_at: timestamp('last_social_request_at'),
})

export const contacts = mysqlTable('contacts', {
  id:                 varchar('id', { length: 36  }).primaryKey(),
  user_id:            varchar('user_id', { length: 36  }).notNull(),
  full_name:          text('full_name').notNull(),
  photo:              varchar('photo', { length: 255 }),
  position:           varchar('position', { length: 255 }),
  company:            varchar('company', { length: 255 }),
  direction:          varchar('direction', { length: 255 }),
  priority:           mysqlEnum('priority', ['high', 'medium', 'low']).notNull().default('medium'),
  relationship_level: mysqlEnum('relationship_level', ['cold', 'warm', 'middle']).notNull().default('cold'),
  last_contact:       date('last_contact', { mode: 'string' }),
  birth_date:         text('birth_date'),
  goals:              text('goals'),
  main_pain:          text('main_pain'),
  interests:          text('interests'),
  dream:              text('dream'),
  personal_traits:    text('personal_traits'),
  useful_to_me:       text('useful_to_me'),
  useful_to_them:     text('useful_to_them'),
  contact_info:       text('contact_info'),
  note:               text('note'),
  important_dates:    text('important_dates'),
  chat_history:       text('chat_history'),
  recent_activity_summary: text('recent_activity_summary'),
  recent_topics:           text('recent_topics'),
  conversation_starters:   text('conversation_starters'),
  tg_activity_summary:     text('tg_activity_summary'),
  tg_recent_topics:        text('tg_recent_topics'),
  tg_conversation_starters: text('tg_conversation_starters'),
  company_about:             text('company_about'),
  company_size:              varchar('company_size', { length: 255 }),
  company_founded:           varchar('company_founded', { length: 20 }),
  company_target_audience:   text('company_target_audience'),
  company_market:            varchar('company_market', { length: 255 }),
  company_technologies:      text('company_technologies'),
  company_revenue:           varchar('company_revenue', { length: 255 }),
  company_competitors:       text('company_competitors'),
  company_requisites:        text('company_requisites'),
  last_vk_analysis_at:       timestamp('last_vk_analysis_at'),
  last_tg_analysis_at:       timestamp('last_tg_analysis_at'),
  created_at:         date('created_at', { mode: 'string' }).notNull(),
})

export const tasks = mysqlTable('tasks', {
  id:           varchar('id', { length: 36  }).primaryKey(),
  user_id:      varchar('user_id', { length: 36  }).notNull(),
  contact_id:   varchar('contact_id', { length: 36  }),
  title:        text('title').notNull(),
  description:  text('description'),
  status:       mysqlEnum('status', ['overdue', 'today', 'this_week', 'no_deadline', 'done']).notNull().default('no_deadline'),
  priority:     mysqlEnum('priority', ['low', 'medium', 'high']).notNull().default('medium'),
  deadline:     datetime('deadline', { mode: 'string' }),
  completed_at: date('completed_at', { mode: 'string' }),
  created_at:   date('created_at', { mode: 'string' }).notNull(),
})

export const auditLog = mysqlTable('audit_log', {
  id:         varchar('id', { length: 36  }).primaryKey(),
  user_id:    varchar('user_id', { length: 36  }).notNull(),
  action:     varchar('action', { length: 100 }).notNull(),
  entity_id:  varchar('entity_id', { length: 36  }),
  ip:         varchar('ip', { length: 50  }),
  created_at: timestamp('created_at').notNull().defaultNow(),
})

export const contactScrapingLogs = mysqlTable('contact_scraping_logs', {
  id:             varchar('id', { length: 36  }).primaryKey(),
  contact_id:     varchar('contact_id', { length: 36  }).notNull(),
  user_id:        varchar('user_id', { length: 36  }).notNull(),
  platform:       mysqlEnum('platform', ['telegram', 'vk', 'website']).notNull(),
  source:         mysqlEnum('source', ['profile', 'group']),
  type:           mysqlEnum('type', ['added', 'conflict', 'error', 'no_changes']).notNull(),
  changes:        json('changes'),
  posts_analyzed: int('posts_analyzed'),
  message:        text('message'),
  created_at:     timestamp('created_at', { fsp: 6 }).notNull().defaultNow(),
})
