import type { TContact } from '@/shared/types/contact.types'
import type { TTask } from '@/shared/types/tasks.types'
import type { TUser } from '@/shared/types/user.types'

export const makeContact = (overrides: Partial<TContact> = {}): TContact => ({
  id:                 'c1',
  user_id:            'u1',
  full_name:          'Иван Иванов',
  photo:              null,
  position:           null,
  company:            null,
  direction:          null,
  priority:           'medium',
  relationship_level: 'cold',
  last_contact:       null,
  birth_date:         null,
  goals:              null,
  main_pain:          null,
  interests:          null,
  dream:              null,
  personal_traits:    null,
  useful_to_me:       null,
  useful_to_them:     null,
  contact_info:       null,
  note:               null,
  important_dates:    [],
  chat_history:       [],
  recent_activity_summary:   null,
  recent_topics:             null,
  conversation_starters:     null,
  last_vk_analysis_at:       null,
  last_tg_analysis_at:       null,
  tg_activity_summary:       null,
  tg_recent_topics:          null,
  tg_conversation_starters:  null,
  company_about:             null,
  company_size:              null,
  company_founded:           null,
  company_target_audience:   null,
  company_market:            null,
  company_technologies:      null,
  company_revenue:           null,
  company_competitors:       null,
  company_requisites:        null,
  created_at:         '2024-01-01',
  ...overrides,
})

export const makeTask = (overrides: Partial<TTask> = {}): TTask => ({
  id:           't1',
  user_id:      'u1',
  contact_id:   null,
  title:        'Задача',
  description:  '',
  status:       'no_deadline',
  priority:     'medium',
  deadline:     null,
  completed_at: null,
  createdAt:    '2024-01-01',
  ...overrides,
})

export const makeUser = (overrides: Partial<TUser> = {}): TUser => ({
  id:               'u1',
  name:             'Иван',
  login:            'ivan@test.com',
  role:             'user',
  image:            null,
  ai_system_prompt: null,
  vk_connected:       false,
  telegram_connected: false,
  ...overrides,
})
